export enum ExceptionMessageCodesEnum {
  success = 'success',
  error = 'error',

  // General
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_COULD_NOT_BE_CREATED = 'USER_COULD_NOT_BE_CREATED',

  PASSWORD_OR_EMAIL_INCORRECT = 'PASSWORD_OR_EMAIL_INCORRECT',

  // Token
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND',

  // GitHub API
  GITHUB_API_RATE_LIMIT_EXCEEDED = 'GITHUB_API_RATE_LIMIT_EXCEEDED',
  GITHUB_API_UNAVAILABLE = 'GITHUB_API_UNAVAILABLE',
  GITHUB_SEARCH_FAILED = 'GITHUB_SEARCH_FAILED',
}
